name: reviewdog
on: [pull_request]
jobs:
  ktlint:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: detekt
        uses: DominuS-RU/Detekt-Action@v1.16.0
        with:
          github_token: ${{ secrets.github_token }}
          reviewdog_reporter: github-pr-check
          detekt_config: config/detekt/config.yml